// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/PubMatic-OpenWrap/prebid-server/modules/pubmatic/openwrap/geodb (interfaces: Geography)

// Package mock_geodb is a generated GoMock package.

//go:build exclude_feature
// +build exclude_feature

package mock_geodb

import (
	go_netacuity_client "git.pubmatic.com/PubMatic/go-netacuity-client"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockGeography is a mock of Geography interface
type MockGeography struct {
	ctrl     *gomock.Controller
	recorder *MockGeographyMockRecorder
}

// MockGeographyMockRecorder is the mock recorder for MockGeography
type MockGeographyMockRecorder struct {
	mock *MockGeography
}

// NewMockGeography creates a new mock instance
func NewMockGeography(ctrl *gomock.Controller) *MockGeography {
	mock := &MockGeography{ctrl: ctrl}
	mock.recorder = &MockGeographyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGeography) EXPECT() *MockGeographyMockRecorder {
	return m.recorder
}

// LookUp mocks base method
func (m *MockGeography) LookUp(arg0 string) (*go_netacuity_client.GeoInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookUp", arg0)
	ret0, _ := ret[0].(*go_netacuity_client.GeoInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookUp indicates an expected call of LookUp
func (mr *MockGeographyMockRecorder) LookUp(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookUp", reflect.TypeOf((*MockGeography)(nil).LookUp), arg0)
}
