name: Validate Merge

on:
  pull_request:
    branches:
      - master
      - main
      - ci

jobs:
  validate-merge:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.4

    - name: Checkout Merged Branch
      uses: actions/checkout@v4

    - name: Validate
      run: |
        git config --global url."https://${USERNAME}:${TOKEN}@git.pubmatic.com".insteadOf "https://git.pubmatic.com"
        ./validate.sh --nofmt --cov --race 10
      env:
        GO111MODULE: "on"
        GOPRIVATE: "git.pubmatic.com/PubMatic/*"
        TOKEN: ${{ secrets.PM_OPENWRAP_CICD_PASSWORD }}
        USERNAME: ${{ secrets.PM_OPENWRAP_CICD_USERNAME }}
